version: "3.8"

services:
  # SLFF
  slff:
    container_name: slff
    build: .
    restart: always
    privileged: true
    volumes:
      - ~/slff-data:/root/slff-data
      - /dev:/dev
    ports:
      - "8100:8100"

  # FTPD
  ftpd:
    container_name: ftpd
    image: stilliard/pure-ftpd
    restart: always
    privileged: false
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ~/slff-data/log:/root/slff-data/log
    environment:
      - FTP_USER_NAME=jasamarga
      - FTP_USER_PASS=jasamarga
      - FTP_USER_HOME=/root/slff-data/log
      - PUBLICHOST=localhost
      - ADDED_FLAGS=-d

  # MySQL
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    privileged: false
    ports:
      - "3306:3306"
    volumes:
      - ~/slff-data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=slff
      - MYSQL_USER=slff
      - MYSQL_PASSWORD=slff

  # Node Exporter
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter
    restart: always
    privileged: false
    network_mode: host
    pid: host
    volumes:
      - /:/rootfs:ro,rslave
    command:
      - --path.rootfs=/rootfs

  # Portainer Agent
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent
    restart: always
    privileged: false
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
