version: "3.8"

services:
  slff-app-docker:
    container_name: slff
    build: .
    restart: always
    privileged: true
    volumes:
      - ~/slff-data:/root/slff-data
      - /dev:/dev
    environment:
      - TZ=Asia/Jakarta

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    privileged: false
    ports:
      - 3306:3306
    volumes:
      - ~/slff-data/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=slff
      - MYSQL_USER=slff
      - MYSQL_PASSWORD=slff

  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter
    restart: always
    privileged: false
    network_mode: host
    pid: host
    volumes:
      - /:/rootfs:ro,rslave
    command:
      - --path.rootfs=/rootfs

  promtail:
    container_name: promtail
    image: grafana/promtail
    restart: always
    privileged: false
    volumes:
      - ~/slff-data:/root/slff-data
      - ~/slff-data/promtail:/mnt/config
      - /var/log:/var/log
    command: 
      - --config.file=/mnt/config/promtail-config.yaml

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: always
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg

  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent
    restart: always
    privileged: false
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
