version: "3.8"

services:
  # SLFF
  slff-app-docker:
    container_name: slff
    build: .
    restart: always
    privileged: true
    volumes:
      - ~/slff-data:/root/slff-data
      - /dev:/dev
    environment:
      - TZ=Asia/Jakarta

  # MySQL
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    privileged: false
    ports:
      - 3306:3306
    volumes:
      - ~/slff-data/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=slff
      - MYSQL_USER=slff
      - MYSQL_PASSWORD=slff

  # Node Exporter
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter
    restart: always
    privileged: false
    network_mode: host
    pid: host
    volumes:
      - /:/rootfs:ro,rslave
    command:
      - --path.rootfs=/rootfs

  # CAdvisor
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: always
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg

  # Loki & Promtail
  loki:
    container_name: loki
    image: grafana/loki
    restart: always
    privileged: false
    ports:
      - 3100:3100
    volumes:
      - ~/slff-data:/root/slff-data
      - ~/slff-data/loki:/mnt/config
    command:
      - --config.file=/mnt/config/loki-config.yaml
  promtail:
    container_name: promtail
    image: grafana/promtail
    restart: always
    privileged: false
    volumes:
      - ~/slff-data:/root/slff-data
      - ~/slff-data/promtail:/mnt/config
    command:
      - --config.file=/mnt/config/promtail-config.yaml

  # Portainer Agent
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent
    restart: always
    privileged: false
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
