name: Docker on Release

on:
  release:
    types:
    - prereleased
    - released

jobs:
  docker-on-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Previous Tag
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1.1"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: protanjung/slff-app-docker:latest,protanjung/slff-app-docker:${{ steps.previous_tag.outputs.tag }}

    - name: Update Repo Description
      uses: peter-evans/dockerhub-description@v2.4.2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: protanjung/slff-app-docker