name: Release Drafter

on:
  push:
    branches: 
     - main
  pull_request:
    types: 
    - opened
    - reopened
    - synchronize

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}